### ISSUE TITLE
Pull information from the sprint issue

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/sprint-helper-bot#17]
- [ ] Get the sprint issue for a given week
  - [ ] Find the right times there (or in the Google Calendar)
  - [ ] Grab:
    - Call title
    - Zoom links
    - Stream links
    - Notes links
  - [ ] Ping the leads for each call using mentions of their IRC names. 

Idea: Give a summary based on the agenda items in the notes.

Sourced from https://github.com/ipfs/pm/issues/234#issuecomment-263315433.

**Comment by Kubuxu** [comment]
Sending stream API to chosen people on Slack would be nice

**Comment by RichardLitt** [comment]
@Kubuxu Sounds like another issue. Not sure I understand what you mean?

**Comment by Kubuxu** [comment]
When you start new Youtube stream it gives you a stream key, currently either me or @dignifiedquire have to login and fetch this key.

**Comment by dignifiedquire** [comment]
no idea if youtube exposes an api to generate events, but it would be great if it is possible
